In [51]:
using JuMP
using Gurobi
using Random
using Distributions

In [52]:
N=6 #No. of nodes (1 supplier + 5 DC's)

K=3 #No. of vehicles

Dk=9000 #Capacity of vehicles increased by 10  times

T=8 #Periods

h=0.025 #Holding cost/unit at each DC

C=[5000 502 488 220 486 742] #Capacity limit for (1 supplier + 5 DC's)

d=[0 0 0 0 0 0 0 0;
75.9 75.9 75.9 75.9 75.9 85.7 85.7 75.9;
62.9 94.8 94.8 94.8 94.8 68.65 36.75 62.9;
67.2 67.2 67.2 67.2 67.2 67.15 67.15 67.2;
102.3 156 156 156 156 119.05 65.35 102.3;
107.4 130.1 130.1 130.1 130.1 65.15 42.45 107.4
] #Demand for each day and (1 supplier + 5 DC's)

c=[
0 140 434 389 419 125;
140 0 300 455 400 97;
434 300 0 609 417 330;
389 455 609 0 256 358;
419 400 417 256 0 316;
125 97 330 358 316 0
] #Transportation cost

std=[
0 0 0 0 0 0 0 0;
11.87 11.87 11.87 11.87 11.87 14.69 14.69 11.87;
10.91 13.89 13.89 13.89 13.89 14.14 11.22 10.91;
11.27 11.27 11.27 11.27 11.27 12.86 12.86 11.27;
13.19 16.03 16.03 16.03 16.03 15.05 11.98 13.19;
13.04 14.00 14.00 14.00 14.00 11.08 9.84 13.04
]# Standard deviation of Demand


I0=[0 98.8 153.9 42.4 23.4 85.7] #Initial inventory
alpha=0.921 # Critical fractile
za=quantile.(Normal(0,1),alpha) #Safety factor
d_new = d + za.*std; #Demand to be satisfied

In [53]:
model=Model(Gurobi.Optimizer)
@variable(model, x[i=1:N,j=1:N,k=1:K,t=1:T], Bin); #If truck k leaves DC i and goes to DC j
@variable(model, y[i=1:N,k=1:K,t=1:T], Bin); #If truck k arrives at DC i
@variable(model, z[j=1:N,k=1:K,t=1:T] >= 0); #Load of truck k when arriving at node j
@variable(model, I[i=1:N,t=0:T] >= 0); #Inventory level at node i till end of period t
@variable(model, q[i=1:N,k=1:K,t=1:T] >= 0); #Quantity delivered to customer i by truck k at start of period t

@objective(model, Min, sum(h*I[i,t] for i=2:N, t=1:T) + sum(c[i,j]*x[i,j,k,t]  for i=1:N, j=1:N, k=1:K, t=1:T))

@constraint(model, [i=2:N], I[i,0] == I0[i]) #Initializing inventory level

@constraint(model, [i=2:N,t=1:T], I[i,t-1] + sum(q[i,k,t] for k=1:K) == I[i,t] + d_new[i,t]); #Balance constraint for each DC

@constraint(model, [i=2:N,t=1:T], I[i,t-1] + sum(q[i,k,t] for k=1:K) <= C[i]); #Capacity constraint for each DC

@constraint(model, [i=2:N,k=1:K,t=1:T], q[i,k,t] <= C[i]*y[i,k,t]); #Constraint which ensures y is 1 when they receive a quantity

@constraint(model, [k=1:K,t=1:T], sum(q[i,k,t] for i=2:N) <= Dk*y[1,k,t]); #If truck delivers from supplier, it has to activate the supplier

@constraint(model, [h=1:N,k=1:K,t=1:T], sum(i == h ? 0 : x[i,h,k,t] for i = 1:N) == y[h,k,t]); #If truck visits DC

@constraint(model, [h=1:N,k=1:K,t=1:T], sum(j == h ? 0 : x[h,j,k,t] for j = 1:N) == y[h,k,t]); #If truck leaves DC

@constraint(model, [i=2:N,j=2:N,k=1:K,t=1:T], z[i,k,t] - d_new[i,t] >= z[j,k,t] - (1-x[i,j,k,t])*sum(d_new)); #To avoid subtours automatically



Set parameter Username
Academic license - for non-commercial use only - expires 2023-03-06


In [54]:
optimize!(model)

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1117 rows, 1350 columns and 4037 nonzeros
Model fingerprint: 0x287ffba5
Variable types: 342 continuous, 1008 integer (1008 binary)
Coefficient statistics:
  Matrix range     [1e+00, 9e+03]
  Objective range  [3e-02, 6e+02]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+01, 4e+03]
Presolve removed 160 rows and 213 columns
Presolve time: 0.01s
Presolved: 957 rows, 1137 columns, 3764 nonzeros
Variable types: 273 continuous, 864 integer (864 binary)

Root relaxation: objective 2.665126e+03, 858 iterations, 0.03 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 2665.12638    0  108          - 2665.12638      -     -    0s
H    0     0                    13272.681430 2665.12638  79.9%     -   

In [55]:
if termination_status(model) == MOI.OPTIMAL
   println("RESULTS:")
   println("Objective = $(objective_value(model))")
else
   println("No solution")
end

println();
    for k=1:K
        has_route = false;
        print("Truck:$(value(k))\n")
        for t=1:T
            print("Day:$(value(t))\n")
            for i=1:N
                for j=1:N
                    if (value(x[i,j,k,t]) == 1)
                        print(j,"->",i,"\n")
                        print("$(value(q[i,k,t]))\n")
                        has_route = true;
                    end
                end
            end
        end
        if has_route
            println();
        end
    end

for i=1:N
    for k=1:K
        for t=1:T
            if (value(q[i,k,t]) > 0)
                println(" Node ",i," Truck ",k," Day ", t," Delivery ",value(q[i,k,t]))
            end
        end
    end
end


for t=1:T
    println("Day", t,)
    for i=2:N
        println("Node ",i," Inventory Level = ",value(I[i,t]))
    end
end


RESULTS:
Objective = 5358.94492881088

Truck:1
Day:1
Day:2
Day:3
4->1
0.0
5->4
166.22264994686822
6->5
357.26327228467426
1->6
712.5426126869536
Day:4
Day:5
Day:6
Day:7
4->1
0.0
5->4
168.41745977009313
1->5
203.18576305069251
Day:8

Truck:2
Day:1
Day:2
Day:3
Day:4
Day:5
4->1
0.0
1->2
398.196413716843
2->3
333.91739668744054
5->4
168.41745977009452
3->5
318.92967880872806
Day:6
Day:7
Day:8

Truck:3
Day:1
6->1
0.0
3->2
271.8336920797232
5->3
267.63402547499254
1->4
123.82264994686905
4->5
276.15367486457365
2->6
189.97588529562182
Day:2
Day:3
Day:4
Day:5
Day:6
Day:7
Day:8

 Node 2 Truck 2 Day 5 Delivery 398.196413716843
 Node 2 Truck 3 Day 1 Delivery 271.8336920797232
 Node 2 Truck 3 Day 3 Delivery 1.5077716852829326e-11
 Node 3 Truck 2 Day 5 Delivery 333.91739668744054
 Node 3 Truck 3 Day 1 Delivery 267.63402547499254
 Node 4 Truck 1 Day 3 Delivery 166.22264994686822
 Node 4 Truck 1 Day 5 Delivery 1.3186701380097268e-12
 Node 4 Truck 1 Day 6 Delivery 2.1538280895286605e-12
 Node 4 Truck

In [56]:
#Truck Capacity utilization
for k=1:K
    println("Truck ",k)
    for t=1:T
        println("on day ",t," utilizes ", value(sum(q[i,k,t] for i=1:N))/value(Dk))
    end
end

Truck 1
on day 1 utilizes 0.0
on day 2 utilizes 0.0
on day 3 utilizes 0.1373365038798329
on day 4 utilizes 0.0
on day 5 utilizes 1.4651890422330297e-16
on day 6 utilizes 2.3931423216985117e-16
on day 7 utilizes 0.041289246980088144
on day 8 utilizes 0.0
Truck 2
on day 1 utilizes 0.0
on day 2 utilizes 0.0
on day 3 utilizes 0.0
on day 4 utilizes 0.0
on day 5 utilizes 0.1354956609981229
on day 6 utilizes 0.0
on day 7 utilizes 0.0
on day 8 utilizes 0.0
Truck 3
on day 1 utilizes 0.12549110307353115
on day 2 utilizes 0.0
on day 3 utilizes 1.6753018725365918e-15
on day 4 utilizes 5.286668947024894e-16
on day 5 utilizes 0.0
on day 6 utilizes 0.0
on day 7 utilizes 1.3470159496980944e-16
on day 8 utilizes 0.0


In [57]:
#Capacity utilization of the DCs
for t=1:T
    println("Day", t,)
    for i=2:N
        println("Node ",i," Inventory Level = ",value(I[i,t])/value(C[i]))
    end
end

Day1
Node 2 Inventory Level = 0.5537355957366307
Node 3 Inventory Level = 0.7033421297734811
Node 4 Inventory Level = 0.3777787498792459
Node 5 Inventory Level = 0.36755480687723857
Node 6 Inventory Level = 0.20197523057279151
Day2
Node 2 Inventory Level = 0.36915706382441044
Node 3 Inventory Level = 0.4688947531823206
Node 4 Inventory Level = 0.0
Node 5 Inventory Level = 0.0
Node 6 Inventory Level = 0.0
Day3
Node 2 Inventory Level = 0.18457853191222012
Node 3 Inventory Level = 0.23444737659116016
Node 4 Inventory Level = 0.3777787498792459
Node 5 Inventory Level = 0.36755480687723524
Node 6 Inventory Level = 0.7583247865255287
Day4
Node 2 Inventory Level = 0.0
Node 3 Inventory Level = 0.0
Node 4 Inventory Level = 0.0
Node 5 Inventory Level = 6.424613737397922e-15
Node 6 Inventory Level = 0.5563495559527373
Day5
Node 2 Inventory Level = 0.6086414157308931
Node 3 Inventory Level = 0.4498095838339228
Node 4 Inventory Level = 0.38775515816663436
Node 5 Inventory Level = 0.2886791001366017

In [58]:
Random.seed!(0);
counter=zeros(6,8)
#probability=zeros(6,8)
for r = 1:10000
    actual_demand = d + randn(6,8).*std;
    for i=1:N
        new_IL=I0[i];
        for t=1:T
            delivered=0;
            for k=1:K
                delivered = delivered + value(q[i,k,t]);
            end
            new_IL=new_IL+delivered-value(actual_demand[i,t]);
            fillrate=(max(value(actual_demand[i,t])+min(new_IL,0),0))/value(actual_demand[i,t]);
            if fillrate>0.95
                counter[i,t]=counter[i,t] + 1
            end
        end
    end
end
probability=counter/10000

6×8 Matrix{Float64}:
 0.0  0.0     0.0  0.0     0.0  0.0     0.0     0.0
 1.0  1.0     1.0  0.9987  1.0  1.0     1.0     1.0
 1.0  1.0     1.0  0.9991  1.0  1.0     0.9996  1.0
 1.0  0.9901  1.0  0.9992  1.0  0.9999  1.0     1.0
 1.0  0.992   1.0  0.9992  1.0  1.0     1.0     1.0
 1.0  0.9926  1.0  1.0     1.0  1.0     1.0     1.0

In [59]:
probability # Probability of meeting the fillrate target

6×8 Matrix{Float64}:
 0.0  0.0     0.0  0.0     0.0  0.0     0.0     0.0
 1.0  1.0     1.0  0.9987  1.0  1.0     1.0     1.0
 1.0  1.0     1.0  0.9991  1.0  1.0     0.9996  1.0
 1.0  0.9901  1.0  0.9992  1.0  0.9999  1.0     1.0
 1.0  0.992   1.0  0.9992  1.0  1.0     1.0     1.0
 1.0  0.9926  1.0  1.0     1.0  1.0     1.0     1.0

In [60]:
safety_stock=za.*std # Safety stock

6×8 Matrix{Float64}:
  0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0
 16.7584  16.7584  16.7584  16.7584  16.7584  20.7398  20.7398  16.7584
 15.4031  19.6103  19.6103  19.6103  19.6103  19.9633  15.8407  15.4031
 15.9113  15.9113  15.9113  15.9113  15.9113  18.1561  18.1561  15.9113
 18.622   22.6316  22.6316  22.6316  22.6316  21.248   16.9137  18.622
 18.4103  19.7656  19.7656  19.7656  19.7656  15.6431  13.8924  18.4103

In [61]:
using DelimitedFiles

In [62]:
writedlm( "3.2a.csv",  safety_stock, ',')